spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

##配置thymeleaf 模板
  thymeleaf:
    mode: HTML5
    cache: false  #开发时把缓存关闭，不然无法实时看见效果
    encoding: UTF-8
    content-type: text/html



server:
  port: 8882
  context-path: /user
  tomcat:
    uri-encoding: utf-8
bc:
  data:
    mybatis:
      base-package: com.bc.spring.thymeleaf.study.common
      type-aliases-package: com.bc.spring.thymeleaf.study.common.entity
      identity: MYSQL
      mapper-locations: classpath*:/mapper/**/*.xml
      check-config-location: false
      not-empty: false

      mappers: org.spring.data.framework.mybatis.bean.IMapper
      config: mybatis-config.xml
eureka:
  instance:
    metadata-map:
      cluster: BC-SPRING-THYMELEAF



